### ISSUE TITLE
Testing 0.6.4 release

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input-manual-tests#10]
## Test plan for Input manual testing

| Test environment  | Value |
|---|---|
| Input Version:  | 0.6.4  |
| Mergin Version:  | 2020.5.6-163-g8e596f9  |
| Mergin URL: <>  | https://dev.dev.cloudmergin.com/  |
|  QGIS Version: |  e29f17cf2f |
| Mergin Plugin Version: |  2020.5.3  |
| Mobile OS:  |  Android arm64-v8a  |
| Date of Execution: | 15/10/2020 |

* For Android please also state type of used architecture ( armeabi-v7a / arm64-v8a )
---

### Test Cases
- [ ] ( #2 ) TC 01: Mergin & Projects Manipulation 
- [x] ( #3 ) TC 02: Sync & Project Status
- [ ] ( #4 ) TC 03: Map Canvas
- [ ] ( #5 ) TC 04: Recording
- [ ] ( #6 ) TC 05: Forms
- [ ] ( #7 ) TC 06: Data Providers
- [ ] ( #8 ) TC 07: Translations

---

| Test Execution Outcome |  |
|---|---|
| Issues Created During Testing:  | |

**Success** * (tested only TC02)
