### ISSUE TITLE
Testing 0.7.2 release - Android arm64-v8

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input-manual-tests#14]
## Test plan for Input manual testing

| Test environment  | Value |
|---|---|
| Input Version:  | 0.7.2  |
| Mergin Version:  | 2020.6.3  |
| Mergin URL: <>  |https://public.cloudmergin.com/   |
|  QGIS Version: | 3.17  |
|  Mergin plugin Version: |  2020.6 |
| Mobile OS: iOS/Android */Windows | Android arm64-v8a  |
| Date of Execution: | 17/11/2020 |

* For Android please also state type of used architecture ( armeabi-v7a / arm64-v8a )
---

### Test Cases
- [ ] ( #2 ) TC 01: Mergin & Projects Manipulation 
- [ ] ( #3 ) TC 02: Sync & Project Status
- [ ] ( #4 ) TC 03: Map Canvas
- [ ] ( #5 ) TC 04: Recording
- [ ] ( #6 ) TC 05: Forms
- [ ] ( #7 ) TC 06: Data Providers
- [ ] ( #8 ) TC 07: Translations

---

| Test Execution Outcome |  |
|---|---|
| Issues Created During Testing:  | LINK TO ISSUE(S) |

**Success** / **Bugs Created** (erase one)
