### ISSUE TITLE
Input Manual Testing Plan

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/input-manual-tests#20]
## Test plan for Input manual testing

| Test environment  | Value |
|---|---|
| Input Version:  |  dc69f04fdb2826c549b3304724b16aba9092e529 |
| Mergin Version:  |   |
| Mergin URL: <>  |   |
|  QGIS Version: |   |
|  Mergin plugin Version: |   |
| Mobile OS: iOS/Android */Windows | Android armeabi-v7a |
| Date of Execution: | 15/1/21 |

* For Android please also state type of used architecture ( armeabi-v7a / arm64-v8a )
---

### Test Cases
- [x] ( #2 ) TC 01: Mergin & Projects Manipulation 
- [x] ( #3 ) TC 02: Sync & Project Status
- [x] ( #4 ) TC 03: Map Canvas
- [ ] ( #5 ) TC 04: Recording
- [ ] ( #6 ) TC 05: Forms
- [ ] ( #7 ) TC 06: Data Providers
- [ ] ( #8 ) TC 07: Translations
- [ ] ( #18 ) TC 08: System Specifics
- [ ] ( #19 ) TC 09: Welcome Screen & Project

---

| Test Execution Outcome |  |
|---|---|
| Issues Created During Testing:  | LINK TO ISSUE(S) |
|  |  |

**Bugs Created**

**Comment by mostlyAtNight** [comment]
* TC.01.C7: `delete project` should now be `Remove from device` ?
* TC.01.C10: Our tour projects are still present - unsure if this is pass or fail - need to make the test more explicit
* TC.01.F: N/A (not tested)
* TC.02.A1: `Project status` should now be `Status` ?
* What happens if there's a downloaded project and the person logs into a different Mergin account?
