### ISSUE TITLE
Test Execution InputApp 0.7.8 (android)

### ISSUE THREAD

**Issue by erpas** [lutraconsulting/input-manual-tests#21]
## Test plan for Input manual testing

| Test environment  | Value |
|---|---|
| Input Version:  |  dc69f04fdb2826c549b3304724b16aba9092e529 arm64-v8a |
| Mergin Version:  |   |
| Mergin URL: <>  |   |
| QGIS Version: |   |
| Mergin plugin Version: |   |
| Mobile OS: | Android arm64-v8a |
| Date of Execution: | 15/1/21 |

---

### Test Cases
- [x] ( #2 ) TC 01: Mergin & Projects Manipulation 
   C10 - the Home page is not empty: `Capturing field data tour` and `Start here!` are there - is it OK?
   F: not available
- [x] ( #3 ) TC 02: Sync & Project Status
   Consider changing the prerequisite to 'User has downloaded HIS project...' otherwise in A8. you won't see any project in My Projects.

- [ ] ( #4 ) TC 03: Map Canvas
- [ ] ( #5 ) TC 04: Recording
- [ ] ( #6 ) TC 05: Forms
- [ ] ( #7 ) TC 06: Data Providers
- [ ] ( #8 ) TC 07: Translations
- [ ] ( #18 ) TC 08: System Specifics
- [ ] ( #19 ) TC 09: Welcome Screen & Project
- [ ] ( #22 ) TC 10: Permissions

---

| Test Execution Outcome |  |
|---|---|
| Issues Created During Testing:  | LINK TO ISSUE(S) |

**Success** / **Bugs Created** (erase one)

**Comment by PeterPetrik** [comment]
can you plase rerun https://github.com/lutraconsulting/input-manual-tests/issues/19
