### ISSUE TITLE
Test Execution InputApp 0.8.0 (android)

### ISSUE THREAD

**Issue by erpas** [lutraconsulting/input-manual-tests#25]
## Test plan for Input manual testing

| Test environment  | Value |
|---|---|
| Input Version:  | e479b4f9628fb71f1daf8b9937ac4db7562b55a9 arm64-v8a  |
| Mergin Version:  |   |
| Mergin URL: <>  |   |
|  QGIS Version: |   |
|  Mergin plugin Version: |   |
| Mobile OS: | Android arm64-v8a |
| Date of Execution: |  03/02/2021 |

---

### Test Cases
- [x] ( #2 ) TC 01: Mergin & Projects Manipulation 
    G10: crash after creating anew feature
- [x] ( #3 ) TC 02: Sync & Project Status
    C: can't sync projects created with wizard.
- [x] ( #4 ) TC 03: Map Canvas
- [x] ( #5 ) TC 04: Recording
- [x] ( #6 ) TC 05: Forms
    A4: Value relation widget - can't set value other than the first from available values
- [x] ( #7 ) TC 06: Data Providers
    missing projects fro tests D, F
- [x] ( #8 ) TC 07: Translations
    My Android only allows for a single language setup. So multiple languages tests were skipped.
- [x] ( #18 ) TC 08: System Specifics
    A: Not giving the permissions makes the app unresponsible
- [x] ( #19 ) TC 09: Welcome Screen & Project
    A3: "Start here!" project on a fresh install users get missing proj datum shift grids
- [x] ( #24 ) TC 10: Proj Tests
    A6 missing datum shift grid
---

| Test Execution Outcome |  |
|---|---|
| Issues Created During Testing:  | https://github.com/lutraconsulting/input/issues/1126 https://github.com/lutraconsulting/input/issues/1127 https://github.com/lutraconsulting/input/issues/1128 https://github.com/lutraconsulting/input/issues/1129 https://github.com/lutraconsulting/input/issues/1130 https://github.com/lutraconsulting/input/issues/1131 |

**Bugs Created**
