### ISSUE TITLE
Test Execution InputApp 0.8.1 (android-arm64) 

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input-manual-tests#30]
## Test plan for Input manual testing

| Test environment  | Value |
|---|---|
| Input Version:  | 0.8.1  |
| Mergin Version:  |  2021.3.1 |
| Mergin URL: <>  | https://public.cloudmergin.com/  |
|  QGIS Version: | 3.18  |
|  Mergin plugin Version: | https://public.cloudmergin.com/  |
| Mobile OS: iOS/Android */Windows | Android - arm64-v8a |
| Date of Execution: | 02/03/2021 |

* For Android please also state type of used architecture ( armeabi-v7a / arm64-v8a )
---

### Test Cases
- [x] ( #2 ) TC 01: Mergin & Projects Manipulation 
- [x] ( #3 ) TC 02: Sync & Project Status
- [x] ( #4 ) TC 03: Map Canvas
- [x] ( #5 ) TC 04: Recording
- [x] ( #6 ) TC 05: Forms
- [x] ( #7 ) TC 06: Data Providers
- [ ] ( #8 ) TC 07: Translations
- [x] ( #18 ) TC 08: System Specifics
- [x] ( #19 ) TC 09: Welcome Screen & Project
- [x] ( #24 ) TC 10: Proj Tests
---

| Test Execution Outcome |  |
|---|---|
| Issues Created During Testing:  | https://github.com/lutraconsulting/input/issues/1212 |

**Bugs Created**
