### ISSUE TITLE
Test Execution InputApp 0.9.3 (iOS)

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/input-manual-tests#34]
## Test plan for Input manual testing

| Test environment  | Value |
|---|---|
| Input Version:  | 0.9.3 *  |
| Mergin Version:  | 2021.4-40-g82fa9a0 ** |
| Mergin URL: <>  | https://dev.dev.cloudmergin.com/  |
|  QGIS Version: | 3.18.1  |
|  Mergin plugin Version: | 2021.1.1  |
| Mobile OS: iOS/Android */Windows | iOS |
| Date of Execution: | 19/04/2021 |

* For Android please also state type of used architecture ( armeabi-v7a / arm64-v8a )
* https://dev.dev.cloudmergin.com/dashboard at the time of testing
---

### Test Cases
- [ ] ( #2 ) TC 01: Mergin & Projects Manipulation 
- [ ] ( #3 ) TC 02: Sync & Project Status
- [ ] ( #4 ) TC 03: Map Canvas
- [ ] ( #5 ) TC 04: Recording
- [ ] ( #6 ) TC 05: Forms
- [ ] ( #7 ) TC 06: Data Providers
- [ ] ( #8 ) TC 07: Translations
- [ ] ( #18 ) TC 08: System Specifics
- [ ] ( #19 ) TC 09: Welcome Screen & Project
- [ ] ( #24 ) TC 10: Proj Tests
---

| Test Execution Outcome |  |
|---|---|
| Issues Created During Testing:  | https://github.com/lutraconsulting/input/issues/1337 |

**Success** / **Bugs Created** (erase one)
