### ISSUE TITLE
Input manual testing (0.9.4 arm64)

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input-manual-tests#35]
## Test plan for Input manual testing

| Test environment  | Value |
|---|---|
| Input Version:  | 0.9.4  |
| Mergin Version:  |  Version: 2021.5.1   |
| Mergin URL: <>  | public.cloudmergin.com  |
|  QGIS Version: | 3.16 LTE  |
|  Mergin plugin Version: | 2021.2.1  |
| Mobile OS: iOS/Android */Windows |  Android - arm64-v8a |
| Date of Execution: | 6.5.2021 |

* For Android please also state type of used architecture ( armeabi-v7a / arm64-v8a )
---

### Test Cases
- [ ] ( #2 ) TC 01: Mergin & Projects Manipulation 
- [ ] ( #3 ) TC 02: Sync & Project Status
- [ ] ( #4 ) TC 03: Map Canvas
- [ ] ( #5 ) TC 04: Recording
- [ ] ( #6 ) TC 05: Forms
- [ ] ( #7 ) TC 06: Data Providers
- [ ] ( #8 ) TC 07: Translations
- [ ] ( #18 ) TC 08: System Specifics
- [ ] ( #19 ) TC 09: Welcome Screen & Project
- [ ] ( #24 ) TC 10: Proj Tests
---

| Test Execution Outcome |  |
|---|---|
| Issues Created During Testing:  | LINK TO ISSUE(S) |

**Success** / **Bugs Created** (erase one)
