### ISSUE TITLE
Test Execution InputApp 0.9.8 (iOS)

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input-manual-tests#38]
| Test environment  | Value |
|---|---|
| Input Version:  |  0.9.8  |
| Mergin Version:  |  Version: 2021.5.1  |
| Mergin URL: <>  | public.cloudmergin.com  |
|  QGIS Version: | 3.16 LTE  |
|  Mergin plugin Version: |  2021.2.1 |
| Mobile OS: | iOS |
| Date of Execution: | 11.6.2021 |

---

### Test Cases
- [ ] ( #2 ) TC 01: Mergin & Projects Manipulation 
- [ ] ( #3 ) TC 02: Sync & Project Status
- [ ] ( #4 ) TC 03: Map Canvas
- [ ] ( #5 ) TC 04: Recording
- [ ] ( #6 ) TC 05: Forms
- [ ] ( #7 ) TC 06: Data Providers
- [ ] ( #8 ) TC 07: Translations
- [ ] ( #18 ) TC 08: System Specifics
- [ ] ( #19 ) TC 09: Welcome Screen & Project
- [ ] ( #24 ) TC 10: Proj Tests
---

| Test Execution Outcome |  |
|---|---|
| Issues Created During Testing:  | LINK TO ISSUE(S) |

Older bugs:

| 1432 | https://github.com/lutraconsulting/input/issues/1432 |
| 1433 | https://github.com/lutraconsulting/input/issues/1433 |
| 1435 | https://github.com/lutraconsulting/input/issues/1435 |
https://github.com/lutraconsulting/input/issues/1389
https://github.com/lutraconsulting/input/issues/1387
https://github.com/lutraconsulting/input/issues/1390

**Bugs Created**
