### ISSUE TITLE
Test Execution InputApp 8a32b03 (android-arm64)

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input-manual-tests#40]
## Test plan for Input manual testing

| Test environment  | Value |
|---|---|
| Input Version:  | 8a32b03 (master version 2nd of July)  |
| Mergin Version:  |  2021.6.2  |
| Mergin URL: <>  | public.cloudmerging.com  |
|  QGIS Version: |  3.16 |
|  Mergin plugin Version: |  2021.3  |
| Mobile OS: iOS/Android */Windows | Android  arm64-v8a |
| Date of Execution: | 2.7.2021 |

---

### Test Cases
- [ ] ( #2 ) TC 01: Mergin & Projects Manipulation 
- [ ] ( #3 ) TC 02: Sync & Project Status
- [ ] ( #4 ) TC 03: Map Canvas
- [ ] ( #5 ) TC 04: Recording
- [ ] ( #6 ) TC 05: Forms
- [ ] ( #7 ) TC 06: Data Providers
- [ ] ( #8 ) TC 07: Translations
- [ ] ( #18 ) TC 08: System Specifics
- [ ] ( #19 ) TC 09: Welcome Screen & Project
- [ ] ( #24 ) TC 10: Proj Tests
- [ ] ( #37 ) TC 11: Subscriptions
---

| Test Execution Outcome |  |
|---|---|
| Issues Created During Testing:  | LINK TO ISSUE(S) |

**Success** / **Bugs Created** (erase one)
