### ISSUE TITLE
Test Execution InputApp 0.9.9  (iOS)

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input-manual-tests#41]
## Test plan for Input manual testing

| Test environment  | Value |
|---|---|
| Input Version:  | 0.9.9 - 2.15.210702185053  |
| Mergin Version:  | 2021.6.2  |
| Mergin URL: <>  | public.cloudmerging.com  |
|  QGIS Version: | 3.16  |
|  Mergin plugin Version: | 2021.3  |
| Mobile OS: iOS   |
| Date of Execution: | 5.7.2021 |
---

### Test Cases
- [ ] ( #2 ) TC 01: Mergin & Projects Manipulation 
- [ ] ( #3 ) TC 02: Sync & Project Status
- [ ] ( #4 ) TC 03: Map Canvas
- [ ] ( #5 ) TC 04: Recording
- [ ] ( #6 ) TC 05: Forms
- [ ] ( #7 ) TC 06: Data Providers
- [ ] ( #8 ) TC 07: Translations
- [ ] ( #18 ) TC 08: System Specifics
- [ ] ( #19 ) TC 09: Welcome Screen & Project
- [ ] ( #24 ) TC 10: Proj Tests
- [ ] ( #37 ) TC 11: Subscriptions
---

| Test Execution Outcome |  |
|---|---|
| Issues Created During Testing:  | LINK TO ISSUE(S) |

**Success** / **Bugs Created** (erase one)
