### ISSUE TITLE
Test Execution InputApp 1.0.0 (iOS)

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input-manual-tests#43]
## Test plan for Input manual testing

| Test environment  | Value |
|---|---|
| Input Version:  | 1.0.0 - 2.15.210820055619  |
| Mergin Version:  |  2021.8   |
| Mergin URL: <>  | public.cloudmerging.com  |
|  QGIS Version: | 3.16  |
|  Mergin plugin Version: | 2021.4.1  |
| Mobile OS: iOS   |
| Date of Execution: | 23.8.2021 |
---

### Test Cases
- [ ] ( #2 ) TC 01: Mergin & Projects Manipulation 
- [ ] ( #3 ) TC 02: Sync & Project Status
- [ ] ( #4 ) TC 03: Map Canvas
- [ ] ( #5 ) TC 04: Recording
- [ ] ( #6 ) TC 05: Forms
- [ ] ( #7 ) TC 06: Data Providers
- [ ] ( #8 ) TC 07: Translations
- [ ] ( #18 ) TC 08: System Specifics
- [ ] ( #19 ) TC 09: Welcome Screen & Project
- [ ] ( #24 ) TC 10: Proj Tests
- [ ] ( #37 ) TC 11: Subscriptions
- [ ] ( #39 ) TC 12: Tickets
---

| Test Execution Outcome |  |
|---|---|
| Issues Created During Testing:  | LINK TO ISSUE(S) |

**Bugs Created**
