### ISSUE TITLE
Test Execution InputApp 1.1.0 (android)

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input-manual-tests#47]
## Test plan for Input manual testing

| Test environment  | Value |
|---|---|
| Input Version:  | 1.1.0 -  e215ad825ade76fc91ecd1ac3a9fea6a35ae19ec |
| Mergin Version:  |  2021.9  |
| Mergin URL: <>  | public.cloudmerging.com  |
|  QGIS Version: | 3.20 |
|  Mergin plugin Version: | 2021.4.1 |
| Mobile OS: | Android 10 - v8a |
| Date of Execution: | 27.10.2021 |
---

### Test Cases
- [x] ( #2 ) TC 01: Mergin & Projects Manipulation 
- [x] ( #3 ) TC 02: Sync & Project Status
- [x] ( #4 ) TC 03: Map Canvas
- [x] ( #5 ) TC 04: Recording
- [x] ( #6 ) TC 05: Forms
- [x] ( #7 ) TC 06: Data Providers
- [x] ( #8 ) TC 07: Translations
- [x] ( #18 ) TC 08: System Specifics - had to be updated!
- [x] ( #19 ) TC 09: Welcome Screen & Project
- [x] ( #46 ) TC 10: Proj Tests
- [x] ( #37 ) TC 11: Subscriptions
- [x] ( #39 ) TC 12: Tickets
---

| Test Execution Outcome |  |
|---|---|
| Issues Created During Testing:  | LINK TO ISSUE(S) |

**Bugs Created**
