### ISSUE TITLE
Test Execution InputApp 1.2.0 (android)

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input-manual-tests#52]
## Test plan for Input manual testing

| Test environment  | Value |
|---|---|
| Input Version:  | 1.2.0. 8bb249d    |
| Mergin Version:  |  2021.11  |
| Mergin URL: <>  |  https://public.cloudmergin.com  |
|  QGIS Version: | 3.16  |
|  Mergin plugin Version: | 2021.4.3   |
| Mobile OS: iOS/Android */Windows | Android arm64-v8a |
| Date of Execution: | 7.12.2021  |

* For Android please also state type of used architecture ( armeabi-v7a / arm64-v8a )
---

### Test Cases
- [ ] ( #2 ) TC 01: Mergin & Projects Manipulation 
- [ ] ( #3 ) TC 02: Sync & Project Status
- [ ] ( #51 ) TC 03: Map Canvas
- [ ] ( #5 ) TC 04: Recording
- [ ] ( #6 ) TC 05: Forms
- [ ] ( #7 ) TC 06: Data Providers
- [ ] ( #8 ) TC 07: Translations
- [ ] ( #18 ) TC 08: System Specifics
- [ ] ( #19 ) TC 09: Welcome Screen & Project
- [ ] ( #46 ) TC 10: Proj Tests
- [ ] ( #50 ) TC 11: Subscriptions
- [ ] ( #48 ) TC 12: Tickets
- [ ] ( #49 ) TC 13: GPS
---

| Test Execution Outcome |  |
|---|---|
| Issues Created During Testing:  | LINK TO ISSUE(S) |

**Success** / **Bugs Created** (erase one)
