### ISSUE TITLE
Test Execution InputApp 1.2.0

### ISSUE THREAD

**Issue by PatrikMizera** [lutraconsulting/input-manual-tests#53]
## Test plan for Input manual testing

| Test environment  | Value |
|---|---|
| Input Version:  | 1.2.0. 8bb249d    |
| Mergin Version:  |  2021.11  |
| Mergin URL: <>  |  https://public.cloudmergin.com  |
|  QGIS Version: | 3.16  |
|  Mergin plugin Version: | 2021.4.3   |
| Mobile OS: iOS/Android */Windows | IOS 15.1 |
| Date of Execution: | 9.12.2021  |

* For Android please also state type of used architecture ( armeabi-v7a / arm64-v8a )
---

### Test Cases
- [x] ( #2 ) TC 01: Mergin & Projects Manipulation 
- [x] ( #3 ) TC 02: Sync & Project Status
- [x] ( #51 ) TC 03: Map Canvas
- [x] ( #5 ) TC 04: Recording
- [x] ( #6 ) TC 05: Forms
- [x] ( #7 ) TC 06: Data Providers
- [x] ( #8 ) TC 07: Translations
- [x] ( #18 ) TC 08: System Specifics
- [x] ( #19 ) TC 09: Welcome Screen & Project
- [x] ( #46 ) TC 10: Proj Tests
- [x] ( #50 ) TC 11: Subscriptions
- [x] ( #48 ) TC 12: Tickets
- [x] ( #49 ) TC 13: GPS
---

| Test Execution Outcome |  |
|---|---|
| 1835 | https://github.com/lutraconsulting/input/issues/1835 |
| 1836 | https://github.com/lutraconsulting/input/issues/1836 |
| Issues Created During Testing:  | LINK TO ISSUE(S) |

**Bugs Created**
