### ISSUE TITLE
Input Manual Testing Plan

### ISSUE THREAD

**Issue by jozef-budac** [lutraconsulting/input-manual-tests#57]
## Test plan for Input manual testing

| Test environment  | Value |
|---|---|
| Input Version:  |   |
| Mergin Version:  |   |
| Mergin URL: <>  |   |
|  QGIS Version: |   |
|  Mergin plugin Version: |   |
| Mobile OS: iOS/Android */Windows |  |
| Date of Execution: |  |

* For Android please also state type of used architecture ( armeabi-v7a / arm64-v8a )
---

### Test Cases
- [ ] ( #2 ) TC 01: Mergin & Projects Manipulation 
- [ ] ( #3 ) TC 02: Sync & Project Status
- [ ] ( #51 ) TC 03: Map Canvas
- [ ] ( #5 ) TC 04: Recording
- [ ] ( #6 ) TC 05: Forms
- [ ] ( #7 ) TC 06: Data Providers
- [ ] ( #8 ) TC 07: Translations
- [ ] ( #18 ) TC 08: System Specifics
- [ ] ( #19 ) TC 09: Welcome Screen & Project
- [ ] ( #46 ) TC 10: Proj Tests
- [ ] ( #50 ) TC 11: Subscriptions
- [ ] ( #48 ) TC 12: Tickets
- [ ] ( #49 ) TC 13: GPS
- [ ] ( #56 ) TC 14: Staking out points
---

| Test Execution Outcome |  |
|---|---|
| Issues Created During Testing:  | LINK TO ISSUE(S) |

**Success** / **Bugs Created** (erase one)
