### ISSUE TITLE
Input Manual Testing Plan

### ISSUE THREAD

**Issue by PatrikMizera** [lutraconsulting/input-manual-tests#60]
## Test plan for Input manual testing

| Test environment  | Value |
|---|---|
| Input Version:  | 1.3.0 |
| Mergin Version:  | 2022.1  |
| Mergin URL: <>  | https://public.cloudmergin.com/dashboard  |
|  QGIS Version: | 3.22.0  |
|  Mergin plugin Version: | 2021.4.3  |
| Mobile OS: iOS/Android */Windows | Android 12 |
| Date of Execution: | 18. February 2022 |
| Architecture | arm64-v8a |

* For Android please also state type of used architecture ( armeabi-v7a / arm64-v8a )
---

### Test Cases
- [ ] ( #2 ) TC 01: Mergin & Projects Manipulation 
- [ ] ( #3 ) TC 02: Sync & Project Status
- [ ] ( #51 ) TC 03: Map Canvas
- [ ] ( #5 ) TC 04: Recording
- [ ] ( #6 ) TC 05: Forms
- [ ] ( #59  ) TC 06: Data Providers
- [ ] ( #8 ) TC 07: Translations
- [ ] ( #18 ) TC 08: System Specifics
- [ ] ( #19 ) TC 09: Welcome Screen & Project
- [ ] ( #46 ) TC 10: Proj Tests
- [ ] ( #50 ) TC 11: Subscriptions
- [ ] ( #48 ) TC 12: Tickets
- [ ] ( #58 ) TC 13: GPS
- [ ] ( #56 ) TC 14: Staking out points
---

| Test Execution Outcome |  | 
|---|---|
| Issues Created During Testing:  | https://github.com/lutraconsulting/input/issues/1952 |

 **Bugs Created**
