### ISSUE TITLE
Test Execution InputApp 1.3.0 (IOS)

### ISSUE THREAD

**Issue by PatrikMizera** [lutraconsulting/input-manual-tests#61]
## Test plan for Input manual testing

| Test environment  | Value |
|---|---|
| Input Version:  | 1.3.0 |
| Mergin Version:  | 2022.1  |
| Mergin URL: <>  | https://public.cloudmergin.com/dashboard  |
|  QGIS Version: | 3.22.0  |
|  Mergin plugin Version: | 2021.4.3  |
| Mobile OS: iOS/Android */Windows | IOS |
| Date of Execution: | 20. February 2022 |

---

### Test Cases
- [x] ( #2 ) TC 01: Mergin & Projects Manipulation 
- [x] ( #3 ) TC 02: Sync & Project Status
- [x] ( #51 ) TC 03: Map Canvas
- [x] ( #5 ) TC 04: Recording
- [x] ( #6 ) TC 05: Forms
- [x] ( #59  ) TC 06: Data Providers
- [x] ( #8 ) TC 07: Translations
- [x] ( #18 ) TC 08: System Specifics
- [x] ( #19 ) TC 09: Welcome Screen & Project
- [x] ( #46 ) TC 10: Proj Tests
- [x] ( #50 ) TC 11: Subscriptions
- [x] ( #48 ) TC 12: Tickets
- [x] ( #58 ) TC 13: GPS
- [x] ( #56 ) TC 14: Staking out points
---

| Test Execution Outcome |  | 
|---|---|
| Issues Created During Testing:  | https://github.com/lutraconsulting/input/issues/1958 |
|                                                    | https://github.com/lutraconsulting/input/issues/1959 |
 **Bugs Created**
